### ISSUE TITLE
No wifi after downgrade

### ISSUE THREAD

**Issue by ozonostudio** [Samgisaninja/SuccessionRestore#101]
I try to downgrade using the version 1.4.10 (because for some reason 1.4.11 stuck on attach) but after the downgrade the wifi not longer works, any fix or suggestion?

**Comment by IMS212** [comment]
Pretty sure this issue was actually fixed in 1.4.11, I can’t help much more with the attach though.

**Comment by ozonostudio** [comment]
> Pretty sure this issue was actually fixed in 1.4.11, I can’t help much more with the attach though.

For some reason the latest version stuck on attachment

**Comment by Samgisaninja** [comment]
This means you forgot to enable the unsupported/hidden downgrade mode. Enable it and it'll work.

**Comment by ozonostudio** [comment]
> This means you forgot to enable the unsupported/hidden downgrade mode. Enable it and it'll work.

No option for that on 1.4.11

**Comment by Samgisaninja** [comment]
[you didn't look very hard](https://twitter.com/samg_is_a_ninja/status/1217990624898621446?s=20)

this is hidden because succession is not a downgrade tool. downgrading is not supported. GL, but don't contact me again about this.
