### ISSUE TITLE
no changes made after restoring

### ISSUE THREAD

**Issue by super-lurker** [Samgisaninja/SuccessionRestore#44]
no changes made after restoring , no setup screen , test mode is off 
wat do

**Comment by Samgisaninja** [comment]
can you send a log?

**Comment by super-lurker** [comment]
> 
> 
> can you send a log?

i fixed it, I disabled some launch daemon from icleaner pro, enabling them all fixed the issue

**Comment by Samgisaninja** [comment]
Ok

**Comment by huynhthanhloc** [comment]
> > can you send a log?
> 
> i fixed it, I disabled some launch daemon from icleaner pro, enabling them all fixed the issue

how to fix it pro? plz , teach me.

**Comment by 4MeInfo** [comment]
iPad Air 2 Cellular 12.1.1 Beta 3 same issue 
https://www.dropbox.com/s/aa5blklvkx13vkp/succession.log?dl=0

**Comment by m1stadev** [comment]
[log](https://www.dropbox.com/s/v83tpl8ik80ffbn/succession.log?dl=0) from 10.3.3 5S that had this issue

**Comment by IMS212** [comment]
I’ll try on my mini 4 WiFi 12.4, I’ll report back in a few hours hopefully

**Comment by jfjjjdi** [comment]
A12 xsmax 12.1.1, the last step in the recovery process cache crashes and flashes back, he didn't reboot for me, can you solve this problem for me?

**Comment by Samgisaninja** [comment]
^was unrelated

I do not know why, but it seems rsync is refusing to delete "non-empty directory". After googling it, this happens when you've blacklisted a file inside a directory, the directory won't be deleted. However, I have not blacklisted *that many* files, so idk what's going on there.

**Comment by Samgisaninja** [comment]
in 1.4.2, there is now at least handling if it happens (succession will immediately stop trying to restore the device so that you don't end up with some crazy half-resotred state and notify the user of the error), but as soon as I implemented that, I have yet to be able to successfully reproduce the issue (I don't think it's resolved as I didn't "do" anything with the intention of solving it, but maybe 🤞)

We'll see ¯\\\_(ツ)_/¯

**Comment by freshkilla** [comment]
Still having this problem have tried with different version. Pretty stuck now. It just Like half deletes things. Is the best way to explain it. When it starts to reboot it just resprings back on. 
iOS 12.1 IPx

**Comment by 0n** [comment]
@Samgisaninja My issue (#83) doesn't seem to be related, I did get a setup screen, I just didn't send screenshots of it as I didn't think I had an issue till I actually saw the jailbreak apps on my homescreen.

**Comment by Samgisaninja** [comment]
it's related, the reason there was no setup screen for the original poster of this issue was because they used an older version where they simultaneously ran into another issue that prevented the setup screen from being shown. That's since been fixed.

**Comment by Samgisaninja** [comment]
this issue has been moved to #89

**Comment by chaqti** [comment]
Can I get some help?

**Comment by chaqti** [comment]
> this issue has been moved to #89

Any fix?
